*** Settings ***
Resource    ${EXECDIR}/elements/home_elements.resource
Resource    ${EXECDIR}/elements/auth_elements.resource
Resource    ${EXECDIR}/elements/contact_elements.resource
Resource    ${EXECDIR}/elements/test_cases_elements.resource
Resource    ${EXECDIR}/elements/products_elements.resource
Resource    ${EXECDIR}/elements/cart_checkout_elements.resource
Resource    ${EXECDIR}/elements/sidebar_elements.resource