name: Robot Framework Tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework robotframework-seleniumlibrary robotframework-faker

      - name: Install Xvfb (Virtual Framebuffer)
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Run Robot Framework Tests
        run: xvfb-run --auto-servernum robot -d results test_cases/test_cases.robot

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-framework-reports
          path: results/